// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains constants.

package bindings

import solanago "github.com/gagliardetto/solana-go"

// Constants defined in the IDL:

var BRIDGE_CPI_AUTHORITY_SEED = []byte{98, 114, 105, 100, 103, 101, 95, 99, 112, 105, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121}
var BRIDGE_SEED = []byte{98, 114, 105, 100, 103, 101}
var INCOMING_MESSAGE_SEED = []byte{105, 110, 99, 111, 109, 105, 110, 103, 95, 109, 101, 115, 115, 97, 103, 101}

const MAX_PARTNER_VALIDATOR_THRESHOLD = uint8(0x5)
const MAX_SIGNER_COUNT = uint8(0x10)

var NATIVE_SOL_PUBKEY = solanago.MustPublicKeyFromBase58("SoL1111111111111111111111111111111111111111")
var OUTGOING_MESSAGE_SEED = []byte{111, 117, 116, 103, 111, 105, 110, 103, 95, 109, 101, 115, 115, 97, 103, 101}
var OUTPUT_ROOT_SEED = []byte{111, 117, 116, 112, 117, 116, 95, 114, 111, 111, 116}
var PARTNER_PROGRAM_ID = solanago.MustPublicKeyFromBase58("S1GN4jus9XzKVVnoHqfkjo1GN8bX46gjXZQwsdGBPHE")
var PARTNER_SIGNERS_ACCOUNT_SEED = []byte{115, 105, 103, 110, 101, 114, 115}

const REMOTE_TOKEN_METADATA_KEY = "remote_token"
const SCALER_EXPONENT_METADATA_KEY = "scaler_exponent"

var SOL_VAULT_SEED = []byte{115, 111, 108, 95, 118, 97, 117, 108, 116}
var TOKEN_VAULT_SEED = []byte{116, 111, 107, 101, 110, 95, 118, 97, 117, 108, 116}
var WRAPPED_TOKEN_SEED = []byte{119, 114, 97, 112, 112, 101, 100, 95, 116, 111, 107, 101, 110}
