// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package bindings

// Account discriminators
var (
	Account_Bridge = [8]byte{231, 232, 31, 98, 110, 3, 23, 59}
)

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_Initialize                  = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_SetAdjustmentDenominator    = [8]byte{31, 91, 190, 63, 164, 7, 31, 150}
	Instruction_SetBlockIntervalRequirement = [8]byte{76, 70, 237, 100, 33, 108, 19, 42}
	Instruction_SetGasCostScaler            = [8]byte{148, 146, 101, 170, 5, 6, 222, 119}
	Instruction_SetGasCostScalerDp          = [8]byte{198, 111, 160, 55, 172, 138, 99, 164}
	Instruction_SetGasFeeReceiver           = [8]byte{58, 188, 230, 188, 47, 188, 79, 154}
	Instruction_SetGasPerCall               = [8]byte{164, 95, 213, 130, 26, 69, 82, 127}
	Instruction_SetGasTarget                = [8]byte{132, 25, 19, 13, 118, 63, 167, 102}
	Instruction_SetMaxCallBufferSize        = [8]byte{140, 178, 4, 238, 245, 66, 117, 189}
	Instruction_SetMinimumBaseFee           = [8]byte{56, 95, 58, 94, 221, 136, 138, 156}
	Instruction_SetOracleSigners            = [8]byte{38, 183, 212, 67, 28, 241, 25, 160}
	Instruction_SetPartnerOracleConfig      = [8]byte{34, 48, 231, 135, 42, 113, 217, 157}
	Instruction_SetPauseStatus              = [8]byte{118, 25, 145, 217, 114, 209, 236, 145}
	Instruction_SetWindowDuration           = [8]byte{229, 2, 41, 119, 55, 255, 252, 205}
	Instruction_TransferGuardian            = [8]byte{118, 250, 162, 85, 197, 130, 116, 123}
)
