// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package bindings

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "initialize" instruction.
// Initializes the bridge program with required state accounts. // This function sets up the initial bridge configuration and must be called once during deployment. //  // # Arguments // * `ctx`      - The context containing all accounts needed for initialization, including the guardian signer // * `guardian` - The guardian account that will have administrative authority over the bridge // * `cfg`      - All the configuration parameters needed to initialize the bridge
func NewInitializeInstruction(
	// Params:
	guardianParam solanago.PublicKey,
	cfgParam Config,

	// Accounts:
	upgradeAuthorityAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	bridgeAccount solanago.PublicKey,
	programDataAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `guardianParam`:
		err = enc__.Encode(guardianParam)
		if err != nil {
			return nil, errors.NewField("guardianParam", err)
		}
		// Serialize `cfgParam`:
		err = enc__.Encode(cfgParam)
		if err != nil {
			return nil, errors.NewField("cfgParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "upgrade_authority": Read-only, Signer, Required
		// The upgrade authority that is authorized to initialize the bridge.
		// This ensures only the program deployer can set the initial configuration.
		accounts__.Append(solanago.NewAccountMeta(upgradeAuthorityAccount, false, true))
		// Account 1 "payer": Writable, Signer, Required
		// The account that pays for the transaction and bridge account creation.
		// Must be mutable to deduct lamports for account rent.
		// Can be different from the upgrade_authority.
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 2 "bridge": Writable, Non-signer, Required
		// The bridge state account being initialized.
		// - Uses PDA with BRIDGE_SEED for deterministic address
		// - Payer funds the account creation
		// - Space allocated for bridge state (DISCRIMINATOR_LEN + Bridge::INIT_SPACE)
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 3 "program_data": Read-only, Non-signer, Required
		// Program data account containing the upgrade authority.
		// Validates that the signer is indeed the upgrade authority.
		accounts__.Append(solanago.NewAccountMeta(programDataAccount, false, false))
		// Account 4 "program": Read-only, Non-signer, Required
		// The bridge program itself.
		// Validates that program_data is the correct ProgramData account for this program.
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		// System program required for creating new accounts.
		// Used internally by Anchor for account initialization.
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_adjustment_denominator" instruction.
// Set the adjustment denominator for EIP-1559 pricing // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_denominator` - The new adjustment denominator
func NewSetAdjustmentDenominatorInstruction(
	// Params:
	newDenominatorParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetAdjustmentDenominator[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newDenominatorParam`:
		err = enc__.Encode(newDenominatorParam)
		if err != nil {
			return nil, errors.NewField("newDenominatorParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_block_interval_requirement" instruction.
// Set the block interval requirement for Protocol Config // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_interval` - The new block interval requirement value
func NewSetBlockIntervalRequirementInstruction(
	// Params:
	newIntervalParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetBlockIntervalRequirement[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newIntervalParam`:
		err = enc__.Encode(newIntervalParam)
		if err != nil {
			return nil, errors.NewField("newIntervalParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_gas_cost_scaler" instruction.
// Set the gas cost scaler for Gas Cost Config // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_scaler` - The new gas cost scaler value
func NewSetGasCostScalerInstruction(
	// Params:
	newScalerParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetGasCostScaler[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newScalerParam`:
		err = enc__.Encode(newScalerParam)
		if err != nil {
			return nil, errors.NewField("newScalerParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_gas_cost_scaler_dp" instruction.
// Set the gas cost scaler DP for Gas Cost Config // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_dp` - The new gas cost scaler DP value
func NewSetGasCostScalerDpInstruction(
	// Params:
	newDpParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetGasCostScalerDp[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newDpParam`:
		err = enc__.Encode(newDpParam)
		if err != nil {
			return nil, errors.NewField("newDpParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_gas_fee_receiver" instruction.
// Set the gas fee receiver for Gas Cost Config // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_receiver` - The new gas fee receiver
func NewSetGasFeeReceiverInstruction(
	// Params:
	newReceiverParam solanago.PublicKey,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetGasFeeReceiver[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newReceiverParam`:
		err = enc__.Encode(newReceiverParam)
		if err != nil {
			return nil, errors.NewField("newReceiverParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_gas_per_call" instruction.
// Set the gas amount per call for Gas Config // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_val` - The new gas amount per call value
func NewSetGasPerCallInstruction(
	// Params:
	newValParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetGasPerCall[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newValParam`:
		err = enc__.Encode(newValParam)
		if err != nil {
			return nil, errors.NewField("newValParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_gas_target" instruction.
// Set the gas target for EIP-1559 pricing // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_target` - The new gas target value
func NewSetGasTargetInstruction(
	// Params:
	newTargetParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetGasTarget[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newTargetParam`:
		err = enc__.Encode(newTargetParam)
		if err != nil {
			return nil, errors.NewField("newTargetParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_max_call_buffer_size" instruction.
// Set the max call buffer size for Buffer Config // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_size` - The new max call buffer size value
func NewSetMaxCallBufferSizeInstruction(
	// Params:
	newSizeParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetMaxCallBufferSize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newSizeParam`:
		err = enc__.Encode(newSizeParam)
		if err != nil {
			return nil, errors.NewField("newSizeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_minimum_base_fee" instruction.
// Set the minimum base fee for EIP-1559 pricing // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_fee` - The new minimum base fee value
func NewSetMinimumBaseFeeInstruction(
	// Params:
	newFeeParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetMinimumBaseFee[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newFeeParam`:
		err = enc__.Encode(newFeeParam)
		if err != nil {
			return nil, errors.NewField("newFeeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_oracle_signers" instruction.
// Sets the authorized oracle EVM signer addresses and the signature threshold used // when registering output roots. This function updates the `OracleSigners` account // and can only be called by the guardian. //  // # Arguments // * `ctx` - The context containing the bridge, guardian signer, and oracle signers accounts // * `cfg` - Configuration parameters for Base oracle signers
func NewSetOracleSignersInstruction(
	// Params:
	cfgParam BaseOracleConfig,

	// Accounts:
	upgradeAuthorityAccount solanago.PublicKey,
	bridgeAccount solanago.PublicKey,
	programDataAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetOracleSigners[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `cfgParam`:
		err = enc__.Encode(cfgParam)
		if err != nil {
			return nil, errors.NewField("cfgParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "upgrade_authority": Read-only, Signer, Required
		// The upgrade authority account
		accounts__.Append(solanago.NewAccountMeta(upgradeAuthorityAccount, false, true))
		// Account 1 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 2 "program_data": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDataAccount, false, false))
		// Account 3 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_partner_oracle_config" instruction.
// Update the partner oracle configuration containing the required signature threshold //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_config` - The new partner oracle config
func NewSetPartnerOracleConfigInstruction(
	// Params:
	newConfigParam PartnerOracleConfig,

	// Accounts:
	upgradeAuthorityAccount solanago.PublicKey,
	bridgeAccount solanago.PublicKey,
	programDataAccount solanago.PublicKey,
	programAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetPartnerOracleConfig[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newConfigParam`:
		err = enc__.Encode(newConfigParam)
		if err != nil {
			return nil, errors.NewField("newConfigParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "upgrade_authority": Read-only, Signer, Required
		// The upgrade authority account
		accounts__.Append(solanago.NewAccountMeta(upgradeAuthorityAccount, false, true))
		// Account 1 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 2 "program_data": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programDataAccount, false, false))
		// Account 3 "program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_pause_status" instruction.
// Set the pause status for the bridge // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_paused` - The new pause status (true for paused, false for unpaused)
func NewSetPauseStatusInstruction(
	// Params:
	newPausedParam bool,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetPauseStatus[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newPausedParam`:
		err = enc__.Encode(newPausedParam)
		if err != nil {
			return nil, errors.NewField("newPausedParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_window_duration" instruction.
// Set the window duration for EIP-1559 pricing // Only the guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and guardian // * `new_duration` - The new window duration in seconds
func NewSetWindowDurationInstruction(
	// Params:
	newDurationParam uint64,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetWindowDuration[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newDurationParam`:
		err = enc__.Encode(newDurationParam)
		if err != nil {
			return nil, errors.NewField("newDurationParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "transfer_guardian" instruction.
// Transfer guardian authority to a new pubkey // Only the current guardian can call this function //  // # Arguments // * `ctx` - The context containing the bridge account and current guardian // * `new_guardian` - The pubkey of the new guardian
func NewTransferGuardianInstruction(
	// Params:
	newGuardianParam solanago.PublicKey,

	// Accounts:
	bridgeAccount solanago.PublicKey,
	guardianAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferGuardian[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newGuardianParam`:
		err = enc__.Encode(newGuardianParam)
		if err != nil {
			return nil, errors.NewField("newGuardianParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "bridge": Writable, Non-signer, Required
		// The bridge account containing configuration
		accounts__.Append(solanago.NewAccountMeta(bridgeAccount, true, false))
		// Account 1 "guardian": Read-only, Signer, Required
		// The guardian account authorized to update configuration
		accounts__.Append(solanago.NewAccountMeta(guardianAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
