// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package bindings

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("6YpL1h2a9u6LuNVi55vAes36xNszt2UDm3Zk1kj4WSBm")
