// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package bindings

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type BaseOracleConfig struct {
	// Number of required valid unique signatures
	Threshold uint8 `json:"threshold"`

	// Number of signers in `signers` array
	SignerCount uint8 `json:"signerCount"`

	// Static list of authorized signer addresses
	Signers [16][20]uint8 `json:"signers"`
}

func (obj BaseOracleConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Threshold`:
	err = encoder.Encode(obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Serialize `SignerCount`:
	err = encoder.Encode(obj.SignerCount)
	if err != nil {
		return errors.NewField("SignerCount", err)
	}
	// Serialize `Signers`:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	return nil
}

func (obj BaseOracleConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BaseOracleConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BaseOracleConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Threshold`:
	err = decoder.Decode(&obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Deserialize `SignerCount`:
	err = decoder.Decode(&obj.SignerCount)
	if err != nil {
		return errors.NewField("SignerCount", err)
	}
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	return nil
}

func (obj *BaseOracleConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BaseOracleConfig: %w", err)
	}
	return nil
}

func UnmarshalBaseOracleConfig(buf []byte) (*BaseOracleConfig, error) {
	obj := new(BaseOracleConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Bridge struct {
	// The Base block number associated with the latest registered output root.
	BaseBlockNumber uint64 `json:"baseBlockNumber"`

	// Incremental nonce assigned to each outgoing message.
	Nonce uint64 `json:"nonce"`

	// Guardian pubkey authorized to update bridge configuration parameters
	Guardian solanago.PublicKey `json:"guardian"`

	// Whether the bridge is paused (emergency stop mechanism)
	Paused bool `json:"paused"`

	// EIP-1559 state and configuration for dynamic pricing.
	Eip1559 Eip1559 `json:"eip1559"`

	// Configuration parameters for outgoing message pricing
	GasConfig GasConfig `json:"gasConfig"`

	// Configuration parameters for bridge protocol
	ProtocolConfig ProtocolConfig `json:"protocolConfig"`

	// Configuration parameters for pre-loading Solana --> Base messages in buffer accounts
	BufferConfig BufferConfig `json:"bufferConfig"`

	// Partner oracle configuration containing the required signature threshold
	PartnerOracleConfig PartnerOracleConfig `json:"partnerOracleConfig"`

	// Configuration parameters for Base oracle signers
	BaseOracleConfig BaseOracleConfig `json:"baseOracleConfig"`
}

func (obj Bridge) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `BaseBlockNumber`:
	err = encoder.Encode(obj.BaseBlockNumber)
	if err != nil {
		return errors.NewField("BaseBlockNumber", err)
	}
	// Serialize `Nonce`:
	err = encoder.Encode(obj.Nonce)
	if err != nil {
		return errors.NewField("Nonce", err)
	}
	// Serialize `Guardian`:
	err = encoder.Encode(obj.Guardian)
	if err != nil {
		return errors.NewField("Guardian", err)
	}
	// Serialize `Paused`:
	err = encoder.Encode(obj.Paused)
	if err != nil {
		return errors.NewField("Paused", err)
	}
	// Serialize `Eip1559`:
	err = encoder.Encode(obj.Eip1559)
	if err != nil {
		return errors.NewField("Eip1559", err)
	}
	// Serialize `GasConfig`:
	err = encoder.Encode(obj.GasConfig)
	if err != nil {
		return errors.NewField("GasConfig", err)
	}
	// Serialize `ProtocolConfig`:
	err = encoder.Encode(obj.ProtocolConfig)
	if err != nil {
		return errors.NewField("ProtocolConfig", err)
	}
	// Serialize `BufferConfig`:
	err = encoder.Encode(obj.BufferConfig)
	if err != nil {
		return errors.NewField("BufferConfig", err)
	}
	// Serialize `PartnerOracleConfig`:
	err = encoder.Encode(obj.PartnerOracleConfig)
	if err != nil {
		return errors.NewField("PartnerOracleConfig", err)
	}
	// Serialize `BaseOracleConfig`:
	err = encoder.Encode(obj.BaseOracleConfig)
	if err != nil {
		return errors.NewField("BaseOracleConfig", err)
	}
	return nil
}

func (obj Bridge) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Bridge: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Bridge) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `BaseBlockNumber`:
	err = decoder.Decode(&obj.BaseBlockNumber)
	if err != nil {
		return errors.NewField("BaseBlockNumber", err)
	}
	// Deserialize `Nonce`:
	err = decoder.Decode(&obj.Nonce)
	if err != nil {
		return errors.NewField("Nonce", err)
	}
	// Deserialize `Guardian`:
	err = decoder.Decode(&obj.Guardian)
	if err != nil {
		return errors.NewField("Guardian", err)
	}
	// Deserialize `Paused`:
	err = decoder.Decode(&obj.Paused)
	if err != nil {
		return errors.NewField("Paused", err)
	}
	// Deserialize `Eip1559`:
	err = decoder.Decode(&obj.Eip1559)
	if err != nil {
		return errors.NewField("Eip1559", err)
	}
	// Deserialize `GasConfig`:
	err = decoder.Decode(&obj.GasConfig)
	if err != nil {
		return errors.NewField("GasConfig", err)
	}
	// Deserialize `ProtocolConfig`:
	err = decoder.Decode(&obj.ProtocolConfig)
	if err != nil {
		return errors.NewField("ProtocolConfig", err)
	}
	// Deserialize `BufferConfig`:
	err = decoder.Decode(&obj.BufferConfig)
	if err != nil {
		return errors.NewField("BufferConfig", err)
	}
	// Deserialize `PartnerOracleConfig`:
	err = decoder.Decode(&obj.PartnerOracleConfig)
	if err != nil {
		return errors.NewField("PartnerOracleConfig", err)
	}
	// Deserialize `BaseOracleConfig`:
	err = decoder.Decode(&obj.BaseOracleConfig)
	if err != nil {
		return errors.NewField("BaseOracleConfig", err)
	}
	return nil
}

func (obj *Bridge) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Bridge: %w", err)
	}
	return nil
}

func UnmarshalBridge(buf []byte) (*Bridge, error) {
	obj := new(Bridge)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type BufferConfig struct {
	// Maximum call buffer size. This caps the max size of a Solana → Base message.
	MaxCallBufferSize uint64 `json:"maxCallBufferSize"`
}

func (obj BufferConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MaxCallBufferSize`:
	err = encoder.Encode(obj.MaxCallBufferSize)
	if err != nil {
		return errors.NewField("MaxCallBufferSize", err)
	}
	return nil
}

func (obj BufferConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BufferConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BufferConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MaxCallBufferSize`:
	err = decoder.Decode(&obj.MaxCallBufferSize)
	if err != nil {
		return errors.NewField("MaxCallBufferSize", err)
	}
	return nil
}

func (obj *BufferConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BufferConfig: %w", err)
	}
	return nil
}

func UnmarshalBufferConfig(buf []byte) (*BufferConfig, error) {
	obj := new(BufferConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Config struct {
	// Configuration parameters for EIP-1559-inspired fee calculations
	Eip1559Config Eip1559Config `json:"eip1559Config"`

	// Configuration parameters for outgoing message pricing
	GasConfig GasConfig `json:"gasConfig"`

	// Configuration parameters for bridge protocol
	ProtocolConfig ProtocolConfig `json:"protocolConfig"`

	// Configuration parameters for pre-loading Solana --> Base messages in buffer accounts
	BufferConfig BufferConfig `json:"bufferConfig"`

	// Partner oracle configuration containing the required signature threshold
	PartnerOracleConfig PartnerOracleConfig `json:"partnerOracleConfig"`

	// Configuration parameters for Base oracle signers
	BaseOracleConfig BaseOracleConfig `json:"baseOracleConfig"`
}

func (obj Config) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Eip1559Config`:
	err = encoder.Encode(obj.Eip1559Config)
	if err != nil {
		return errors.NewField("Eip1559Config", err)
	}
	// Serialize `GasConfig`:
	err = encoder.Encode(obj.GasConfig)
	if err != nil {
		return errors.NewField("GasConfig", err)
	}
	// Serialize `ProtocolConfig`:
	err = encoder.Encode(obj.ProtocolConfig)
	if err != nil {
		return errors.NewField("ProtocolConfig", err)
	}
	// Serialize `BufferConfig`:
	err = encoder.Encode(obj.BufferConfig)
	if err != nil {
		return errors.NewField("BufferConfig", err)
	}
	// Serialize `PartnerOracleConfig`:
	err = encoder.Encode(obj.PartnerOracleConfig)
	if err != nil {
		return errors.NewField("PartnerOracleConfig", err)
	}
	// Serialize `BaseOracleConfig`:
	err = encoder.Encode(obj.BaseOracleConfig)
	if err != nil {
		return errors.NewField("BaseOracleConfig", err)
	}
	return nil
}

func (obj Config) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Config: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Config) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Eip1559Config`:
	err = decoder.Decode(&obj.Eip1559Config)
	if err != nil {
		return errors.NewField("Eip1559Config", err)
	}
	// Deserialize `GasConfig`:
	err = decoder.Decode(&obj.GasConfig)
	if err != nil {
		return errors.NewField("GasConfig", err)
	}
	// Deserialize `ProtocolConfig`:
	err = decoder.Decode(&obj.ProtocolConfig)
	if err != nil {
		return errors.NewField("ProtocolConfig", err)
	}
	// Deserialize `BufferConfig`:
	err = decoder.Decode(&obj.BufferConfig)
	if err != nil {
		return errors.NewField("BufferConfig", err)
	}
	// Deserialize `PartnerOracleConfig`:
	err = decoder.Decode(&obj.PartnerOracleConfig)
	if err != nil {
		return errors.NewField("PartnerOracleConfig", err)
	}
	// Deserialize `BaseOracleConfig`:
	err = decoder.Decode(&obj.BaseOracleConfig)
	if err != nil {
		return errors.NewField("BaseOracleConfig", err)
	}
	return nil
}

func (obj *Config) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Config: %w", err)
	}
	return nil
}

func UnmarshalConfig(buf []byte) (*Config, error) {
	obj := new(Config)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Eip1559 struct {
	// Configuration parameters for EIP-1559-inspired fee calculations
	Config Eip1559Config `json:"config"`

	// Current base fee used in fee computation (runtime state).
	// Unitless value combined with `gas_per_call` and gas cost scaler to produce lamports.
	CurrentBaseFee uint64 `json:"currentBaseFee"`

	// Gas used in the current time window (runtime state)
	CurrentWindowGasUsed uint64 `json:"currentWindowGasUsed"`

	// Unix timestamp when the current window started (runtime state)
	WindowStartTime int64 `json:"windowStartTime"`
}

func (obj Eip1559) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Config`:
	err = encoder.Encode(obj.Config)
	if err != nil {
		return errors.NewField("Config", err)
	}
	// Serialize `CurrentBaseFee`:
	err = encoder.Encode(obj.CurrentBaseFee)
	if err != nil {
		return errors.NewField("CurrentBaseFee", err)
	}
	// Serialize `CurrentWindowGasUsed`:
	err = encoder.Encode(obj.CurrentWindowGasUsed)
	if err != nil {
		return errors.NewField("CurrentWindowGasUsed", err)
	}
	// Serialize `WindowStartTime`:
	err = encoder.Encode(obj.WindowStartTime)
	if err != nil {
		return errors.NewField("WindowStartTime", err)
	}
	return nil
}

func (obj Eip1559) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Eip1559: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Eip1559) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Config`:
	err = decoder.Decode(&obj.Config)
	if err != nil {
		return errors.NewField("Config", err)
	}
	// Deserialize `CurrentBaseFee`:
	err = decoder.Decode(&obj.CurrentBaseFee)
	if err != nil {
		return errors.NewField("CurrentBaseFee", err)
	}
	// Deserialize `CurrentWindowGasUsed`:
	err = decoder.Decode(&obj.CurrentWindowGasUsed)
	if err != nil {
		return errors.NewField("CurrentWindowGasUsed", err)
	}
	// Deserialize `WindowStartTime`:
	err = decoder.Decode(&obj.WindowStartTime)
	if err != nil {
		return errors.NewField("WindowStartTime", err)
	}
	return nil
}

func (obj *Eip1559) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Eip1559: %w", err)
	}
	return nil
}

func UnmarshalEip1559(buf []byte) (*Eip1559, error) {
	obj := new(Eip1559)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Eip1559Config struct {
	// Gas target per window
	Target uint64 `json:"target"`

	// Adjustment denominator (controls rate of change)
	Denominator uint64 `json:"denominator"`

	// Window duration in seconds
	WindowDurationSeconds uint64 `json:"windowDurationSeconds"`

	// Minimum base fee. Used to seed `current_base_fee` at initialization
	// and as an underflow clamp during decreases; not enforced as a strict lower bound
	// on every step.
	MinimumBaseFee uint64 `json:"minimumBaseFee"`
}

func (obj Eip1559Config) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Target`:
	err = encoder.Encode(obj.Target)
	if err != nil {
		return errors.NewField("Target", err)
	}
	// Serialize `Denominator`:
	err = encoder.Encode(obj.Denominator)
	if err != nil {
		return errors.NewField("Denominator", err)
	}
	// Serialize `WindowDurationSeconds`:
	err = encoder.Encode(obj.WindowDurationSeconds)
	if err != nil {
		return errors.NewField("WindowDurationSeconds", err)
	}
	// Serialize `MinimumBaseFee`:
	err = encoder.Encode(obj.MinimumBaseFee)
	if err != nil {
		return errors.NewField("MinimumBaseFee", err)
	}
	return nil
}

func (obj Eip1559Config) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Eip1559Config: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Eip1559Config) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Target`:
	err = decoder.Decode(&obj.Target)
	if err != nil {
		return errors.NewField("Target", err)
	}
	// Deserialize `Denominator`:
	err = decoder.Decode(&obj.Denominator)
	if err != nil {
		return errors.NewField("Denominator", err)
	}
	// Deserialize `WindowDurationSeconds`:
	err = decoder.Decode(&obj.WindowDurationSeconds)
	if err != nil {
		return errors.NewField("WindowDurationSeconds", err)
	}
	// Deserialize `MinimumBaseFee`:
	err = decoder.Decode(&obj.MinimumBaseFee)
	if err != nil {
		return errors.NewField("MinimumBaseFee", err)
	}
	return nil
}

func (obj *Eip1559Config) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Eip1559Config: %w", err)
	}
	return nil
}

func UnmarshalEip1559Config(buf []byte) (*Eip1559Config, error) {
	obj := new(Eip1559Config)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type GasConfig struct {
	// Scaling factor applied when converting (gas_per_call * base_fee) into lamports
	GasCostScaler uint64 `json:"gasCostScaler"`

	// Decimal precision for the gas cost scaler (denominator)
	GasCostScalerDp uint64 `json:"gasCostScalerDp"`

	// Account that receives gas fees collected on Solana
	GasFeeReceiver solanago.PublicKey `json:"gasFeeReceiver"`

	// Amount of gas per Solana --> Base message
	GasPerCall uint64 `json:"gasPerCall"`
}

func (obj GasConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `GasCostScaler`:
	err = encoder.Encode(obj.GasCostScaler)
	if err != nil {
		return errors.NewField("GasCostScaler", err)
	}
	// Serialize `GasCostScalerDp`:
	err = encoder.Encode(obj.GasCostScalerDp)
	if err != nil {
		return errors.NewField("GasCostScalerDp", err)
	}
	// Serialize `GasFeeReceiver`:
	err = encoder.Encode(obj.GasFeeReceiver)
	if err != nil {
		return errors.NewField("GasFeeReceiver", err)
	}
	// Serialize `GasPerCall`:
	err = encoder.Encode(obj.GasPerCall)
	if err != nil {
		return errors.NewField("GasPerCall", err)
	}
	return nil
}

func (obj GasConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding GasConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *GasConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `GasCostScaler`:
	err = decoder.Decode(&obj.GasCostScaler)
	if err != nil {
		return errors.NewField("GasCostScaler", err)
	}
	// Deserialize `GasCostScalerDp`:
	err = decoder.Decode(&obj.GasCostScalerDp)
	if err != nil {
		return errors.NewField("GasCostScalerDp", err)
	}
	// Deserialize `GasFeeReceiver`:
	err = decoder.Decode(&obj.GasFeeReceiver)
	if err != nil {
		return errors.NewField("GasFeeReceiver", err)
	}
	// Deserialize `GasPerCall`:
	err = decoder.Decode(&obj.GasPerCall)
	if err != nil {
		return errors.NewField("GasPerCall", err)
	}
	return nil
}

func (obj *GasConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling GasConfig: %w", err)
	}
	return nil
}

func UnmarshalGasConfig(buf []byte) (*GasConfig, error) {
	obj := new(GasConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PartnerOracleConfig struct {
	// Partner signatures required by our bridge to accept an output root
	RequiredThreshold uint8 `json:"requiredThreshold"`
}

func (obj PartnerOracleConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RequiredThreshold`:
	err = encoder.Encode(obj.RequiredThreshold)
	if err != nil {
		return errors.NewField("RequiredThreshold", err)
	}
	return nil
}

func (obj PartnerOracleConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PartnerOracleConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PartnerOracleConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RequiredThreshold`:
	err = decoder.Decode(&obj.RequiredThreshold)
	if err != nil {
		return errors.NewField("RequiredThreshold", err)
	}
	return nil
}

func (obj *PartnerOracleConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PartnerOracleConfig: %w", err)
	}
	return nil
}

func UnmarshalPartnerOracleConfig(buf []byte) (*PartnerOracleConfig, error) {
	obj := new(PartnerOracleConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type ProtocolConfig struct {
	// Block interval requirement for output root registration. Every Base block associated with a
	// submitted output root must be a multiple of this number.
	BlockIntervalRequirement uint64 `json:"blockIntervalRequirement"`

	// The Base evm address of SOL
	RemoteSolAddress [20]uint8 `json:"remoteSolAddress"`
}

func (obj ProtocolConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `BlockIntervalRequirement`:
	err = encoder.Encode(obj.BlockIntervalRequirement)
	if err != nil {
		return errors.NewField("BlockIntervalRequirement", err)
	}
	// Serialize `RemoteSolAddress`:
	err = encoder.Encode(obj.RemoteSolAddress)
	if err != nil {
		return errors.NewField("RemoteSolAddress", err)
	}
	return nil
}

func (obj ProtocolConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ProtocolConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ProtocolConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `BlockIntervalRequirement`:
	err = decoder.Decode(&obj.BlockIntervalRequirement)
	if err != nil {
		return errors.NewField("BlockIntervalRequirement", err)
	}
	// Deserialize `RemoteSolAddress`:
	err = decoder.Decode(&obj.RemoteSolAddress)
	if err != nil {
		return errors.NewField("RemoteSolAddress", err)
	}
	return nil
}

func (obj *ProtocolConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ProtocolConfig: %w", err)
	}
	return nil
}

func UnmarshalProtocolConfig(buf []byte) (*ProtocolConfig, error) {
	obj := new(ProtocolConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
